//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPExtensionManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPExtensionManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP Extension Manager.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while locating &quot;{0}&quot; at:
        ///{1}.
        /// </summary>
        public static string DebugTextErrorDirectoryNotFound {
            get {
                return ResourceManager.GetString("DebugTextErrorDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For VP14 and later.
        /// </summary>
        public static string EnumDescriptionVPVersionMagix {
            get {
                return ResourceManager.GetString("EnumDescriptionVPVersionMagix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For VP13 and earlier.
        /// </summary>
        public static string EnumDescriptionVPVersionSony {
            get {
                return ResourceManager.GetString("EnumDescriptionVPVersionSony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown VP version.
        /// </summary>
        public static string EnumDescriptionVPVersionUnknown {
            get {
                return ResourceManager.GetString("EnumDescriptionVPVersionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download link not found.
        /// </summary>
        public static string ErrorDownloadLinkNotFound {
            get {
                return ResourceManager.GetString("ErrorDownloadLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InstallWindowCancelButton {
            get {
                return ResourceManager.GetString("InstallWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force re-download the latest version.
        /// </summary>
        public static string InstallWindowForceReDownloadText {
            get {
                return ResourceManager.GetString("InstallWindowForceReDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install path.
        /// </summary>
        public static string InstallWindowInstallPathText {
            get {
                return ResourceManager.GetString("InstallWindowInstallPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string InstallWindowOKButton {
            get {
                return ResourceManager.GetString("InstallWindowOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP version.
        /// </summary>
        public static string InstallWindowVPVersionText {
            get {
                return ResourceManager.GetString("InstallWindowVPVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Paths.
        /// </summary>
        public static string MainPageInstallPathsText {
            get {
                return ResourceManager.GetString("MainPageInstallPathsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall {0} ({1}).
        /// </summary>
        public static string MessageBoxTitleUninstall {
            get {
                return ResourceManager.GetString("MessageBoxTitleUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} from the following path?
        ///- {1}.
        /// </summary>
        public static string MessageBoxUninstallContent {
            get {
                return ResourceManager.GetString("MessageBoxUninstallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This might also remove the following items:
        ///{0}.
        /// </summary>
        public static string MessageBoxUninstallDependencyText {
            get {
                return ResourceManager.GetString("MessageBoxUninstallDependencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while looking up this app on GitHub:
        ///- {0}.
        /// </summary>
        public static string NotificationErrorCheckingForLatestVersion {
            get {
                return ResourceManager.GetString("NotificationErrorCheckingForLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find a download link for {0} for version {1}.
        /// </summary>
        public static string NotificationErrorDownloadNotFoundForVP {
            get {
                return ResourceManager.GetString("NotificationErrorDownloadNotFoundForVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while installing &quot;{0} ({1})&quot;:.
        /// </summary>
        public static string NotificationErrorDuringInstall {
            get {
                return ResourceManager.GetString("NotificationErrorDuringInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uninstalling &quot;{0} ({1})&quot;:
        ///&gt; close VEGAS Pro if it&apos;s open.
        /// </summary>
        public static string NotificationErrorDuringUninstall {
            get {
                return ResourceManager.GetString("NotificationErrorDuringUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating &quot;{0} ({1})&quot;:.
        /// </summary>
        public static string NotificationErrorDuringUpdate {
            get {
                return ResourceManager.GetString("NotificationErrorDuringUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while looking up &quot;{0}&quot; on GitHub:.
        /// </summary>
        public static string NotificationErrorGitHubLookup {
            get {
                return ResourceManager.GetString("NotificationErrorGitHubLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub API rate limit exceeded, remaining minutes until reset: {0:0.00}.
        /// </summary>
        public static string NotificationErrorGitHubRateLimited {
            get {
                return ResourceManager.GetString("NotificationErrorGitHubRateLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while searching for &quot;{0}&quot;:.
        /// </summary>
        public static string NotificationErrorSearchingInstall {
            get {
                return ResourceManager.GetString("NotificationErrorSearchingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while searching in &quot;{0}&quot; at:
        ///{1}.
        /// </summary>
        public static string NotificationErrorSearchingInstallAtPath {
            get {
                return ResourceManager.GetString("NotificationErrorSearchingInstallAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads folder was changed.
        /// </summary>
        public static string NotificationInfoDownloadsChanged {
            get {
                return ResourceManager.GetString("NotificationInfoDownloadsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads folder was reset to:
        ///{0}.
        /// </summary>
        public static string NotificationInfoDownloadsReset {
            get {
                return ResourceManager.GetString("NotificationInfoDownloadsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}
        ///Click here to download from GitHub.
        /// </summary>
        public static string NotificationInfoNewVersionAvailable {
            get {
                return ResourceManager.GetString("NotificationInfoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will open a link to the latest version.
        /// </summary>
        public static string NotificationInfoOpenVersion {
            get {
                return ResourceManager.GetString("NotificationInfoOpenVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0}x {1}.
        /// </summary>
        public static string NotificationSuccessFoundInstall {
            get {
                return ResourceManager.GetString("NotificationSuccessFoundInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed {0} ({1}).
        /// </summary>
        public static string NotificationSuccessInstalled {
            get {
                return ResourceManager.GetString("NotificationSuccessInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled {0} from the selected path.
        /// </summary>
        public static string NotificationSuccessUninstalled {
            get {
                return ResourceManager.GetString("NotificationSuccessUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version for {0}: {1}.
        /// </summary>
        public static string NotificationSuccessUpdateAvailable {
            get {
                return ResourceManager.GetString("NotificationSuccessUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0} to {1}.
        /// </summary>
        public static string NotificationSuccessUpdated {
            get {
                return ResourceManager.GetString("NotificationSuccessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version.
        /// </summary>
        public static string NotificationSuccessUsingLatestVersion {
            get {
                return ResourceManager.GetString("NotificationSuccessUsingLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VP Extension Manager by RatinFX.
        /// </summary>
        public static string SettingsPageAboutCreatorText {
            get {
                return ResourceManager.GetString("SettingsPageAboutCreatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the GitHub page for more information..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update on Start.
        /// </summary>
        public static string SettingsPageCheckForUpdateOnStartText {
            get {
                return ResourceManager.GetString("SettingsPageCheckForUpdateOnStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string SettingsPageDownloadsText {
            get {
                return ResourceManager.GetString("SettingsPageDownloadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select versions....
        /// </summary>
        public static string SettingsPageInstalledVPVersionsEmptySelectText {
            get {
                return ResourceManager.GetString("SettingsPageInstalledVPVersionsEmptySelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed VP versions.
        /// </summary>
        public static string SettingsPageInstalledVPVersionsText {
            get {
                return ResourceManager.GetString("SettingsPageInstalledVPVersionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string ShellMenuItemSettingsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemSettingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string TextCheckForUpdate {
            get {
                return ResourceManager.GetString("TextCheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TextDownload {
            get {
                return ResourceManager.GetString("TextDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        public static string TextDownloadUpdate {
            get {
                return ResourceManager.GetString("TextDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For VP13 and below.
        /// </summary>
        public static string TextForVP13AndBelow {
            get {
                return ResourceManager.GetString("TextForVP13AndBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For VP14 and above.
        /// </summary>
        public static string TextForVP14AndAbove {
            get {
                return ResourceManager.GetString("TextForVP14AndAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub error.
        /// </summary>
        public static string TextGitHubError {
            get {
                return ResourceManager.GetString("TextGitHubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string TextInstall {
            get {
                return ResourceManager.GetString("TextInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version not found.
        /// </summary>
        public static string TextLatestVersionNotFound {
            get {
                return ResourceManager.GetString("TextLatestVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple installs.
        /// </summary>
        public static string TextMultipleInstalls {
            get {
                return ResourceManager.GetString("TextMultipleInstalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string TextNotInstalled {
            get {
                return ResourceManager.GetString("TextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TextOpen {
            get {
                return ResourceManager.GetString("TextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string TextRefresh {
            get {
                return ResourceManager.GetString("TextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TextRemove {
            get {
                return ResourceManager.GetString("TextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string TextReset {
            get {
                return ResourceManager.GetString("TextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on PC.
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string TextUnknownError {
            get {
                return ResourceManager.GetString("TextUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TextUpdate {
            get {
                return ResourceManager.GetString("TextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Notes.
        /// </summary>
        public static string TextUpdateNotes {
            get {
                return ResourceManager.GetString("TextUpdateNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install {0}.
        /// </summary>
        public static string WindowTitleInstall {
            get {
                return ResourceManager.GetString("WindowTitleInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string WindowTitleUpdate {
            get {
                return ResourceManager.GetString("WindowTitleUpdate", resourceCulture);
            }
        }
    }
}
